var botao_criptografar = document.getElementById("criptografar")
var botao_descriptografar = document.getElementById("descriptografar") 
var botao_reload = document.getElementById("recarregar")
var botao_copiar = document.getElementById("copiar") 
var div_botao = document.getElementById("secao-botao")
var resultado = document.getElementById("resultado")
var caixatexto = document.getElementById("mensagem") 